/* Contenuto del sito. Tutto il testo visibile di prodotti e ordine sta qui,
   separato dal layout. */

window.IS7 = {
  instagram: "https://www.instagram.com/italyshop_7/",
  dm: "https://ig.me/m/italyshop_7",
  handle: "@italyshop_7",
  // Numero WhatsApp di Francesco con prefisso internazionale (es. "393331234567").
  // Se è vuoto, gli ordini vanno su Instagram.
  whatsapp: "",

  ui: {
    price: "Prezzo in DM",
    add: "Aggiungi all'ordine",
    added: "Aggiunto all'ordine",
    ask: "Chiedi su Instagram",
    noteLabel: "Taglia e colore che cerchi",
    notePlaceholder: "Es.: 42, nera",
    seen: "Cosa si vede nella foto",
    photo: "Foto",
    cartTitle: "Il tuo ordine",
    cartUnit: ["articolo", "articoli"],
    cartSumTail: "prezzo in DM",
    cartNoNote: "Taglia e colore da confermare",
    nameErr: "Scrivi nome e cognome, così sappiamo chi fa l'ordine.",
    phoneErr: "Manca il numero di telefono completo, con prefisso.",
    cartEmpty: "Non hai ancora aggiunto niente. Scegli un articolo dal catalogo e lo ritrovi qui.",
    cartNote: "Sul sito non si paga niente. Mandi questo ordine in DM e Francesco ti risponde con prezzo, taglie disponibili e spedizione.",
    cartSend: "Conferma su Instagram",
    cartSendWa: "Conferma su WhatsApp",
    sending: "Invio dell'ordine…",
    cartEmptyErr: "Aggiungi almeno un articolo all'ordine.",
    cartDoneWa: "Si è aperto WhatsApp con l'ordine già scritto: tocca «Invia».",
    cartClear: "Svuota l'ordine",
    remove: "Rimuovi",
    copied: "Ordine copiato. Incollalo nella chat di Instagram che si è appena aperta.",
    cartDone: "Ordine copiato. Nella chat di @italyshop_7 tieni premuto e scegli «Incolla».",
    copyFail: "Non è stato possibile copiarlo in automatico. Seleziona il testo dell'ordine e copialo.",
    msgHello: "Ciao Francesco, ti scrivo dal sito di Italy Shop 7. Mi interessa:",
    msgNote: "taglia/colore",
    msgBye: "Mi mandi prezzo e disponibilità? Grazie.",
    pill: "Il mio ordine",
    back: "Torna al catalogo",
    priceLine: "<b>Prezzo:</b> te lo conferma Francesco in DM.",
    color: "Colore",
    colorSeen: "Colori che si vedono nei video. Scegli quello che ti interessa.",
    anyColor: "Secondo l'account, questo modello si trova in qualsiasi taglia e colore.",
    sizeLabel: "Taglia che cerchi",
    sizeHint: "Non è uno stock pubblicato: la disponibilità si conferma in DM.",
    sizePh: { sneakers: "Es.: 42", abbigliamento: "Es.: M", accessori: "", orologi: "" },
    dm: "Chiedi in DM",
    dmHello: "Ciao Francesco, ti scrivo dal sito di Italy Shop 7. Mi interessa:",
    dmCopied: "Richiesta copiata. Incollala nella chat di Instagram che si è appena aperta.",
    specs: { brand: "Marchio", cat: "Categoria", colors: "Colori visti", size: "Taglia", includes: "Include", detail: "Dettaglio", price: "Prezzo", photo: "Foto" },
    sizeAsk: "Da chiedere",
    sizeAny: "Qualsiasi taglia, secondo l'account",
    priceDm: "In DM",
    nextTitle: "Come si procede",
    next: ["Lo aggiungi all'ordine o chiedi direttamente.", "Mandi il messaggio a @italyshop_7 su Instagram.", "Francesco ti conferma prezzo, taglia e consegna."],
    moreTitle: "Potrebbe interessarti anche",
    aboutTitle: "Il modello",
    seenTitle: "Cosa si vede nel video",
    msgTitle: "Il tuo messaggio a Francesco",
    msgHint: "Si copia da solo quando tocchi «Chiedi in DM». Scegli colore e taglia e si completa.",
    photoFrom: "Foto",
    prev: "Precedente",
    nextItem: "Successivo",
    of: "di",
    photos: "foto",
  },

  /* Campione di colore per ogni nome usato nei prodotti (due toni = metà e metà). */
  swatches: {
    "Nero": "#151515", "Total black": "#000000", "Bianco": "#ffffff", "Bianco e beige": ["#ffffff", "#cdb89a"],
    "Bianco con tallone nero": ["#ffffff", "#151515"], "Bianco e grigio": ["#ffffff", "#9a9a98"], "Panna": "#efe8d6",
    "Blu navy": "#1f2a44", "Verde": "#2f6b3a", "Beige": "#cdb89a", "Azzurro": "#9cc9e8", "Rosa": "#e9a3bd",
    "Verde acqua": "#6fcfb9", "Lilla": "#c7b7e6", "Verde chiaro": "#b9e38a",
  },

  categories: [
    { id: "sneakers", name: "Sneakers" },
    { id: "abbigliamento", name: "Abbigliamento" },
    { id: "orologi", name: "Orologi" },
    { id: "accessori", name: "Accessori" },
  ],

  /* img: nome base in /img (esiste in -400 e -720 salvo single).
     seen: solo ciò che si vede nelle foto o che dice l'account; niente di supposto. */
  products: [
    {
      id: "lv-skate", cat: "sneakers", brand: "Louis Vuitton", name: "LV Skate",
      imgs: ["lv-1", "hero-lv"], ratio: "9/16",
      seen: ["Nel video compaiono in nero, total black, bianco e beige, e bianco", "Colori: chiedi quale c'è nella tua taglia"],
      source: "Reel Instagram, 4 set 2026",
      about: "Sneaker di ispirazione skate di Louis Vuitton: silhouette ampia e imbottita, lacci spessi e il fiore del monogramma sul lato.",
      colors: ["Nero", "Total black", "Bianco e beige", "Bianco"],
    },
    {
      id: "mcq-graffiti", cat: "sneakers", brand: "Alexander McQueen", name: "Oversized, suola Graffiti",
      imgs: ["mcq-graffiti-1", "mcq-graffiti-2"], ratio: "9/16",
      seen: ["Colore nero", "Logo sulla suola"],
      source: "Reel Instagram, 4 set 2026",
      about: "La Oversized di Alexander McQueen, con la suola extra alta del marchio e il logo scritto in stile graffiti lungo tutta la suola.",
      colors: ["Nero"],
      detail: "Logo Graffiti sulla suola",
    },
    {
      id: "balenciaga-track", cat: "sneakers", brand: "Balenciaga", name: "Track",
      imgs: ["balenciaga-1"], ratio: "9/16",
      seen: ["Colore nero", "Taglia 43 segnata sulla soletta del paio in foto"],
      source: "Reel Instagram, 4 set 2026",
      about: "Sneaker di Balenciaga dall'estetica tecnica, ispirata alle scarpe da trekking e da running: strati sovrapposti di rete e nylon su una suola spessa e dentellata.",
      colors: ["Nero"],
      size: "Il paio in foto è taglia 43",
    },
    {
      id: "mcq-oversized", cat: "sneakers", brand: "Alexander McQueen", name: "Oversized",
      imgs: ["mcq-oversized"], single: 450, ratio: "1/1",
      seen: ["Bianca con tallone nero", "Con scatola, dust bag e card del marchio"],
      source: "Post Instagram, 29 ago 2026",
      about: "Il modello più conosciuto di Alexander McQueen: pelle liscia, profilo pulito e la suola in gomma extra alta che gli dà il nome.",
      colors: ["Bianco con tallone nero"],
      includes: "Scatola, dust bag e card del marchio",
    },
    {
      id: "versace-white", cat: "sneakers", brand: "Versace", name: "Chain Reaction bianca",
      imgs: ["versace-white-2", "versace-white-1"], ratio: "3/4",
      seen: ["Colore bianco", "Con cartellino"],
      source: "Reel Instagram, 4 set 2026",
      about: "Modello di Versace disegnato insieme a Salehe Bembury. La suola, alta e a gradini, si ispira agli anelli di una catena: da qui il nome.",
      colors: ["Bianco"],
      includes: "Cartellino",
    },
    {
      id: "versace-black", cat: "sneakers", brand: "Versace", name: "Chain Reaction nera",
      imgs: ["versace-black-1", "versace-black-2"], ratio: "3/4",
      seen: ["Colore nero", "Con cartellino"],
      source: "Reel Instagram, 4 set 2026",
      about: "Modello di Versace disegnato insieme a Salehe Bembury. La suola, alta e a gradini, si ispira agli anelli di una catena: da qui il nome.",
      colors: ["Nero"],
      includes: "Cartellino",
    },
    {
      id: "dior-b22", cat: "sneakers", brand: "Dior", name: "B22",
      imgs: ["dior-b22"], ratio: "3/4",
      seen: ["Bianca e grigia", "Con shopper e scatola Dior"],
      source: "Reel Instagram, 4 set 2026",
      about: "Sneaker di Dior dalla silhouette voluminosa, che unisce rete tecnica e pelle su una suola spessa.",
      colors: ["Bianco e grigio"],
      includes: "Shopper e scatola Dior",
    },

    {
      id: "prada-set", cat: "abbigliamento", brand: "Prada", name: "Completo camicia e bermuda",
      imgs: ["prada-set"], ratio: "1/1",
      seen: ["Nero in foto", "Secondo l'account: «qualsiasi taglia o colorazione»"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Nero"],
      any: true,
      detail: "Camicia e bermuda coordinati",
    },
    {
      id: "rl-hoodie", cat: "abbigliamento", brand: "Ralph Lauren", name: "Tuta con cappuccio",
      imgs: ["rl-hoodie"], ratio: "1/1",
      seen: ["Panna in foto", "Secondo l'account: qualsiasi taglia e colore"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Panna"],
      any: true,
      detail: "Felpa con cappuccio e pantalone",
    },
    {
      id: "lacoste-set", cat: "abbigliamento", brand: "Lacoste", name: "Completo t-shirt e bermuda",
      imgs: ["lacoste-set"], ratio: "1/1",
      seen: ["Nel video: bianco, blu navy, nero e verde"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Bianco", "Blu navy", "Nero", "Verde"],
      detail: "T-shirt e bermuda",
    },
    {
      id: "lacoste-mono", cat: "abbigliamento", brand: "Lacoste", name: "Completo monogram",
      imgs: ["lacoste-mono-beige", "lacoste-mono-navy"], ratio: "1/1",
      seen: ["Beige e blu navy", "Bermuda con banda laterale"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Beige", "Blu navy"],
      detail: "Bermuda con banda laterale",
    },
    {
      id: "stone-island", cat: "abbigliamento", brand: "Stone Island", name: "Completo t-shirt e bermuda",
      imgs: ["stone-island"], ratio: "1/1",
      seen: ["Nel video: azzurro, nero, rosa e verde acqua", "Patch del marchio su manica e bermuda"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Azzurro", "Nero", "Rosa", "Verde acqua"],
      detail: "Patch del marchio su manica e bermuda",
    },
    {
      id: "cg-tee", cat: "abbigliamento", brand: "Canada Goose", name: "T-shirt con patch",
      imgs: ["canada-goose-tee"], ratio: "1/1",
      seen: ["Lilla in foto", "Patch sul petto"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Lilla"],
      detail: "Patch sul petto",
    },

    {
      id: "ms-pink", cat: "orologi", brand: "Swatch × Omega", name: "MoonSwatch Mission to the Pink Moonphase",
      imgs: ["ms-pink"], ratio: "9/16",
      seen: ["Rosa", "Con scatola e scontrino"],
      source: "Reel Instagram, 4 set 2026",
      about: "Collaborazione tra Swatch e Omega che reinterpreta lo Speedmaster Moonwatch: cronografo al quarzo con cassa in bioceramica da 42 mm. Questa versione aggiunge l'indicatore delle fasi lunari.",
      colors: ["Rosa"],
      includes: "Scatola e scontrino",
    },
    {
      id: "ms-earth", cat: "orologi", brand: "Swatch × Omega", name: "MoonSwatch Mission on Earth",
      imgs: ["ms-earth"], ratio: "9/16",
      seen: ["Verde acqua", "Con scatola e scontrino"],
      source: "Reel Instagram, 4 set 2026",
      about: "Collaborazione tra Swatch e Omega che reinterpreta lo Speedmaster Moonwatch: cronografo al quarzo con cassa in bioceramica da 42 mm.",
      colors: ["Verde acqua"],
      includes: "Scatola e scontrino",
    },
    {
      id: "ms-white", cat: "orologi", brand: "Swatch × Omega", name: "MoonSwatch Mission to the Moonphase",
      imgs: ["ms-white"], ratio: "9/16",
      seen: ["Bianco, cinturino in velcro", "Con scatola"],
      source: "Reel Instagram, 4 set 2026",
      about: "Collaborazione tra Swatch e Omega che reinterpreta lo Speedmaster Moonwatch: cronografo al quarzo con cassa in bioceramica da 42 mm. Questa versione aggiunge l'indicatore delle fasi lunari.",
      colors: ["Bianco"],
      includes: "Scatola",
      detail: "Cinturino in velcro",
    },
    {
      id: "ms-green", cat: "orologi", brand: "Swatch × Omega", name: "MoonSwatch verde chiaro",
      imgs: ["ms-green"], ratio: "9/16",
      seen: ["Cassa verde chiaro, quadrante nero", "Con custodia"],
      source: "Reel Instagram, 4 set 2026",
      about: "Collaborazione tra Swatch e Omega che reinterpreta lo Speedmaster Moonwatch: cronografo al quarzo con cassa in bioceramica da 42 mm.",
      colors: ["Verde chiaro"],
      includes: "Custodia",
      detail: "Quadrante nero",
    },
    {
      id: "ms-black", cat: "orologi", brand: "Swatch × Omega", name: "MoonSwatch nero",
      imgs: ["ms-black"], ratio: "9/16",
      seen: ["Nero, cinturino in velcro", "Con scatola e scontrino"],
      source: "Reel Instagram, 4 set 2026",
      about: "Collaborazione tra Swatch e Omega che reinterpreta lo Speedmaster Moonwatch: cronografo al quarzo con cassa in bioceramica da 42 mm.",
      colors: ["Nero"],
      includes: "Scatola e scontrino",
      detail: "Cinturino in velcro",
    },

    {
      id: "gorros", cat: "accessori", brand: "Vari marchi", name: "Berretti di lana",
      imgs: ["gorros"], ratio: "1/1",
      seen: ["Neri, con logo Canada Goose, Ralph Lauren, Lacoste e Moncler"],
      source: "Reel Instagram, 4 set 2026",
      colors: ["Nero"],
      detail: "Loghi Canada Goose, Ralph Lauren, Lacoste e Moncler",
    },
  ],
};
